const features=[
  ["◈","أموالك الشخصية","تابع الدخل والمصروف والميزانيات وأهداف الادخار في مكان واحد."],
  ["⌂","المنزل والعائلة","وزّع التكاليف وتابع الفواتير ومساهمات أفراد الأسرة بشفافية."],
  ["✈","السفر والمجموعات","مساهمات، مصروفات، تعويضات وتسويات ذكية بين جميع الأعضاء."],
  ["◎","الجمعيات الدورية","أقساط وأدوار وقرعة إلكترونية موثقة وتقارير لكل مساهم."],
  ["▥","إيصالات وكشوفات","اطبع وحمّل إيصالات القبض والصرف والتسليم وكشوف الحساب."],
  ["⚿","صلاحيات دقيقة","مالك ومدير وأمين صندوق ومدقق وعضو، بصلاحيات قابلة للتخصيص."],
];
export default function Landing(){return <main className="landing" dir="rtl"><nav className="public-nav"><a className="public-logo" href="/"><span>ر</span><div><b>رِفد</b><small>RIFD · OMAN</small></div></a><div className="public-links"><a href="#features">المزايا</a><a href="/pricing">الباقات</a><a href="#security">الأمان</a><a href="#about">عن رِفد</a></div><div className="public-actions"><a href="/admin">دخول الإدارة</a><a className="fill" href="/dashboard">تسجيل الدخول</a></div></nav><div className="flagline"><i/><i/><i/></div>
<section className="hero"><div className="hero-copy"><em>منصة مالية عُمانية للأفراد والمجموعات</em><h1>أدر أموالك المشتركة<br/><span>بوضوح وثقة.</span></h1><p>رِفد يجمع المحافظ الشخصية والمنزلية، الرحلات، الجمعيات والمصاريف الجماعية في منصة واحدة آمنة وسهلة.</p><div className="hero-actions"><a href="/dashboard">ابدأ مجاناً ←</a><a className="light" href="/pricing">شاهد الباقات</a></div><small>✓ لا تحتاج بطاقة بنكية للبدء &nbsp; ✓ بياناتك خاصة وآمنة</small></div><div className="hero-visual"><div className="mock"><header><span>ر</span><b>مرحباً عبدالحميد</b><i>🇴🇲 OMR</i></header><div className="mock-kpis"><article><small>صافي أموالي</small><b>5,320.000 ر.ع</b><em>+7.8%</em></article><article><small>المحافظ النشطة</small><b>4</b><em>كلها منتظمة</em></article></div><section><b>محافظي</b>{[["✈","سفرة العائلة","1,240 ر.ع"],["⌂","مصاريف المنزل","680 ر.ع"],["◎","جمعية الإخوة","3,600 ر.ع"]].map(x=><div key={x[1]}><span>{x[0]}</span><p><b>{x[1]}</b><small>نشطة</small></p><strong>{x[2]}</strong></div>)}</section></div><div className="float-card"><span>✓</span><p><b>تم استلام مساهمة</b><small>50.000 ر.ع · الآن</small></p></div></div></section>
<section className="trust"><p>مناسب للأفراد والعائلات والجمعيات وفرق العمل في دول الخليج</p><div><span>🇴🇲 عُمان</span><span>🇦🇪 الإمارات</span><span>🇸🇦 السعودية</span><span>🇶🇦 قطر</span><span>🇧🇭 البحرين</span><span>🇰🇼 الكويت</span><span>🇺🇸 الدولار</span></div></section>
<section className="feature-section" id="features"><div className="section-intro"><em>كل ما تحتاجه</em><h2>من المحفظة الشخصية إلى إدارة أكبر مجموعة</h2><p>محرك مالي موحد يفصل الأموال الشخصية عن المشتركة ويحفظ كل حركة في سجل واضح.</p></div><div className="feature-grid">{features.map(f=><article key={f[1]}><i>{f[0]}</i><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section>
<section className="how"><div><em>كيف يعمل رِفد؟</em><h2>ابدأ في ثلاث خطوات</h2><p>اختر نوع المحفظة، أضف أعضاءك، واترك لرِفد مهمة الحساب والتنظيم والتوثيق.</p><a href="/dashboard">جرّب لوحة المستخدم ←</a></div><ol><li><b>01</b><div><h3>أنشئ مساحتك المالية</h3><p>شخصية، منزلية، سفر، جمعية أو مشروع مشترك.</p></div></li><li><b>02</b><div><h3>حدد القواعد والصلاحيات</h3><p>المساهمات والدورية ومن يرى أو يعتمد كل عملية.</p></div></li><li><b>03</b><div><h3>تابع واطبع التقارير</h3><p>أرصدة لحظية، إيصالات رسمية وكشوفات قابلة للتنزيل.</p></div></li></ol></section>
<section className="security" id="security"><div><small>حماية وشفافية</small><h2>سجل مالي لا يضيع فيه شيء</h2><p>كل عملية موثقة بمن أنشأها واعتمدها، مع سجل تعديلات وصلاحيات دقيقة وموافقات على العمليات الحساسة.</p></div><div className="security-cards"><article>⚿<b>صلاحيات حسب الدور</b><small>تحكم في المشاهدة والإضافة والاعتماد</small></article><article>◉<b>سجل تدقيق شامل</b><small>توثيق كل تعديل وإلغاء وتسوية</small></article><article>▥<b>مستندات قابلة للطباعة</b><small>إيصالات وكشوفات بتسلسل مرجعي</small></article></div></section>
<section className="cta"><div><span>ر</span><h2>ابدأ تنظيم أموالك اليوم</h2><p>الخطة المجانية تكفي لتجربة رِفد دون بطاقة بنكية.</p><a href="/dashboard">إنشاء حساب مجاني ←</a></div></section>
<footer><a className="public-logo" href="/"><span>ر</span><div><b>رِفد</b><small>RIFD · OMAN</small></div></a><p>منصة عُمانية لإدارة الأموال الشخصية والمشتركة.</p><div><a href="/pricing">الباقات</a><a href="/dashboard">لوحة المستخدم</a><a href="/admin">لوحة الإدارة</a><a href="/documents">المستندات</a></div><small>© 2026 رِفد. جميع الحقوق محفوظة.</small></footer></main>}
