"use client";
import { useState } from "react";

export function AdminPanel({money,flash}:{money:(n:number)=>string;flash:(s:string)=>void}){
  const [tab,setTab]=useState("overview");
  return <div className="admin-panel">
    <div className="heading admin-heading"><div><p>رِفد / الإدارة المركزية</p><h1>إدارة منصة رِفد</h1><span>متابعة العملاء والاشتراكات والإيرادات والصلاحيات</span></div><div><button>⇩ تقرير الإدارة</button><button className="admin-primary" onClick={()=>flash("تم فتح إنشاء باقة جديدة")}>＋ إنشاء باقة</button></div></div>
    <div className="admin-tabs">{[["overview","نظرة عامة"],["plans","الباقات"],["coupons","الكوبونات"],["users","المستخدمون"],["roles","الصلاحيات"]].map(x=><button className={tab===x[0]?"on":""} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>
    {tab==="overview"&&<AdminOverview money={money}/>} {tab==="plans"&&<PlanManager flash={flash}/>} {tab==="coupons"&&<CouponManager flash={flash}/>} {tab==="users"&&<UserManager/>} {tab==="roles"&&<RoleManager/>}
  </div>
}

function AKpi({label,value,note,icon}:{label:string;value:string;note:string;icon:string}){return <article className="admin-kpi"><div><span>{label}</span><i>{icon}</i></div><b>{value}</b><small>{note}</small></article>}
function AdminOverview({money}:{money:(n:number)=>string}){return <><div className="admin-kpis"><AKpi label="إجمالي العملاء" value="1,248" note="+86 هذا الشهر" icon="♙"/><AKpi label="الاشتراكات النشطة" value="876" note="70.2% من العملاء" icon="▣"/><AKpi label="الإيراد الشهري" value={money(9842)} note="+14.6% عن يوليو" icon="↙"/><AKpi label="اشتراكات ستنتهي" value="43" note="خلال 7 أيام" icon="◷"/></div><div className="admin-grid"><section className="panel"><div className="panel-head"><div><h2>نمو الإيرادات</h2><p>الإيراد الشهري المتكرر خلال 6 أشهر</p></div></div><div className="revenue-bars">{[42,49,57,66,75,88].map((x,i)=><div key={i}><i style={{height:`${x}%`}}/><span>{["مارس","أبريل","مايو","يونيو","يوليو","أغسطس"][i]}</span></div>)}</div></section><section className="panel plan-share"><div className="panel-head"><div><h2>توزيع المشتركين</h2><p>حسب الباقة الحالية</p></div></div>{[["البداية",372,30],["النخبة",418,34],["التميز",327,26],["الريادة",131,10]].map(p=><div className="share" key={p[0]}><span>{p[0]}</span><i><em style={{width:`${p[2]}%`}}/></i><b>{p[1]}</b></div>)}</section></div><section className="panel admin-feed"><div className="panel-head"><div><h2>آخر نشاطات الاشتراك</h2><p>الترقيات والتجديدات والإلغاءات</p></div></div>{[["شركة الأفق","ترقية إلى الريادة","+99.99 ر.ع"],["أحمد البلوشي","تجديد باقة النخبة","+9.99 ر.ع"],["سارة الهنائية","استخدمت كوبون OMAN20","−20%"],["محمد الرواحي","ألغى التجديد التلقائي","—"]].map(x=><div key={x[0]}><span>{x[0][0]}</span><p><b>{x[0]}</b><small>{x[1]}</small></p><strong>{x[2]}</strong></div>)}</section></>}

function PlanManager({flash}:{flash:(s:string)=>void}){const plans=[["البداية","مجانية","1 محفظة · عضوان"],["النخبة","9.99 ر.ع / شهر","5 محافظ · 15 عضواً"],["التميز","29.99 ر.ع / شهر","20 محفظة · 75 عضواً"],["الريادة","99.99 ر.ع / شهر","غير محدود · فرق عمل"]];return <><SectionTools title="الباقات والحدود" desc="تحكم في السعر والمزايا وحدود الاستخدام والصلاحيات لكل باقة" action="＋ باقة جديدة"/><div className="plan-admin-grid">{plans.map((p,i)=><article className={i===2?"featured":""} key={p[0]}><div><b>{p[0]}</b><em>نشطة</em></div><h3>{p[1]}</h3><p>{p[2]}</p><ul><li>المحافظ الجماعية <b>{i===0?"—":i+2}</b></li><li>تصدير التقارير <b>{i?"✓":"—"}</b></li><li>القرعة والتصويت <b>{i>1?"✓":"—"}</b></li><li>الموافقات المتعددة <b>{i>2?"✓":"—"}</b></li></ul><button onClick={()=>flash(`تعديل باقة ${p[0]}`)}>تعديل السعر والمزايا</button></article>)}</div><section className="panel permission-matrix"><div className="panel-head"><div><h2>مصفوفة مزايا الباقات</h2><p>تتحول المزايا تلقائياً إلى صلاحيات داخل حساب المشترك</p></div><button>حفظ</button></div><table><thead><tr><th>الميزة</th><th>البداية</th><th>النخبة</th><th>التميز</th><th>الريادة</th></tr></thead><tbody>{["محفظة شخصية","محفظة منزلية","محافظ السفر","الجمعيات","صلاحيات مخصصة","تقارير متقدمة","API"].map((f,i)=><tr key={f}><td>{f}</td>{[0,1,2,3].map(p=><td key={p}><input type="checkbox" defaultChecked={p>=Math.floor(i/2)}/></td>)}</tr>)}</tbody></table></section></>}
function CouponManager({flash}:{flash:(s:string)=>void}){return <><SectionTools title="الخصومات والكوبونات" desc="خصم نسبي أو ثابت مع شروط وحدود استخدام" action="＋ كوبون جديد"/><div className="coupon-stats"><div><b>12</b><span>فعالة</span></div><div><b>327</b><span>مرة استخدام</span></div><div><b>1,482 ر.ع</b><span>إجمالي الخصم</span></div><div><b>24.6%</b><span>معدل التحويل</span></div></div><section className="panel coupons"><table><thead><tr><th>الكود</th><th>الخصم</th><th>الباقات</th><th>الاستخدام</th><th>الصلاحية</th><th>الحالة</th></tr></thead><tbody>{[["OMAN20","20%","التميز والريادة","84 / 200","31 ديسمبر","فعال"],["WELCOME10","10%","الكل","173 / 500","مستمر","فعال"],["ANNUAL25","25%","السنوي","49 / 100","30 سبتمبر","فعال"],["EID2026","5 ر.ع","النخبة","21 / 50","منتهي","منتهي"]].map(c=><tr key={c[0]}><td><code>{c[0]}</code></td>{c.slice(1).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></section><div className="coupon-rules">{[["％","نوع الخصم","نسبة أو مبلغ ثابت"],["◷","الصلاحية","تاريخ بداية ونهاية"],["♙","حد الاستخدام","إجمالي ولكل مستخدم"],["▣","الباقات","باقات ومدد محددة"]].map(x=><article key={x[1]}><i>{x[0]}</i><b>{x[1]}</b><p>{x[2]}</p></article>)}</div></>}
function UserManager(){return <><SectionTools title="المستخدمون والعملاء" desc="إدارة الحسابات والاشتراكات وحالات الدفع" action="⇩ تصدير"/><section className="panel users-table"><table><thead><tr><th>العميل</th><th>الباقة</th><th>الفوترة</th><th>التجديد</th><th>الاستخدام</th><th>الحالة</th></tr></thead><tbody>{[["عبدالله الشحي","التميز","سنوي","12 مايو 2027","12 / 20","نشط"],["مريم الزدجالية","النخبة","شهري","28 أغسطس","4 / 5","نشط"],["شركة الأفق","الريادة","سنوي","10 أغسطس 2027","34 عضواً","نشط"],["أحمد البلوشي","البداية","—","—","1 / 1","مجاني"],["سارة الهنائية","التميز","شهري","فشل الدفع","8 / 20","مراجعة"]].map(u=><tr key={u[0]}>{u.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></section></>}
function RoleManager(){return <><SectionTools title="أدوار إدارة المنصة" desc="منفصلة تماماً عن صلاحيات أعضاء المحافظ" action="＋ دور إداري"/><div className="admin-roles">{[["♛","المدير العام","كل الصلاحيات"],["▣","مدير الاشتراكات","الباقات والكوبونات"],["♙","خدمة العملاء","الحسابات والدعم"],["◈","المحاسب","الفواتير والإيرادات"],["◉","المراقب","قراءة السجلات"]].map(r=><article key={r[1]}><span>{r[0]}</span><div><b>{r[1]}</b><p>{r[2]}</p></div><button>تعديل الصلاحيات</button></article>)}</div></>}
function SectionTools({title,desc,action}:{title:string;desc:string;action:string}){return <div className="section-tools"><div><h2>{title}</h2><p>{desc}</p></div><button>{action}</button></div>}

export function PricingView({flash}:{flash:(s:string)=>void}){const [annual,setAnnual]=useState(true);const plans=[{n:"البداية",p:0,d:"لبداية تنظيم أموالك",f:["محفظة شخصية","عضوان","تقارير أساسية"]},{n:"النخبة",p:9.99,d:"للأفراد والعائلات",f:["5 محافظ","15 عضواً","السفر والجمعيات","تصدير التقارير"]},{n:"التميز",p:29.99,d:"لمديري المجموعات",f:["20 محفظة","75 عضواً","القرعة والتصويت","تقارير وصلاحيات متقدمة"]},{n:"الريادة",p:99.99,d:"للفرق والمؤسسات",f:["استخدام غير محدود","موافقات متعددة","سجل تدقيق","API ودعم أولوية"]}];return <div className="pricing-page"><div className="pricing-hero"><small>خطط واضحة بلا رسوم خفية</small><h1>اختر الباقة التي تنمو مع احتياجك</h1><p>ابدأ مجاناً وانتقل إلى الباقة المناسبة عندما تحتاج مزايا أكثر.</p><div className="billing-toggle"><button className={!annual?"on":""} onClick={()=>setAnnual(false)}>شهري</button><button className={annual?"on":""} onClick={()=>setAnnual(true)}>سنوي <em>وفر 20%</em></button></div></div><div className="pricing-grid">{plans.map((p,i)=><article className={i===2?"popular":""} key={p.n}>{i===2&&<span className="popular-tag">الأكثر اختياراً</span>}<small>باقة</small><h2>{p.n}</h2><p>{p.d}</p><div className="price"><b>{p.p===0?"مجاناً":(annual?p.p*.8:p.p).toFixed(2)}</b>{p.p>0&&<span>ر.ع / شهرياً</span>}</div>{annual&&p.p>0&&<em className="annual-price">تُدفع سنوياً · {(p.p*.8*12).toFixed(2)} ر.ع</em>}<button onClick={()=>flash(`تم اختيار باقة ${p.n}`)}>{p.p===0?"ابدأ مجاناً":"اشترك الآن"}</button><ul>{p.f.map(f=><li key={f}>✓ {f}</li>)}</ul></article>)}</div><div className="coupon-box"><div><span>％</span><p><b>لديك كوبون؟</b><small>أدخل الرمز لمشاهدة السعر بعد الخصم</small></p></div><input placeholder="رمز الكوبون"/><button onClick={()=>flash("تم تطبيق خصم 20%")}>تطبيق</button></div><section className="pricing-faq"><h2>أسئلة الاشتراك</h2><div><article><b>هل يمكن تغيير الباقة؟</b><p>الترقية فورية، والتخفيض يبدأ مع دورة الفوترة التالية.</p></article><article><b>ماذا يحدث عند الانتهاء؟</b><p>تبقى البيانات محفوظة للقراءة وتتوقف المزايا الإضافية.</p></article><article><b>هل الأسعار تشمل الضريبة؟</b><p>تظهر الضريبة ورسوم الدفع حسب دولة المشترك قبل السداد.</p></article></div></section></div>}
