/** ITU-style dial codes for member phones / WhatsApp. Default: Oman (+968). */

export type CountryDial = {
  iso2: string;
  dial: string;
  nameAr: string;
  nameEn: string;
};

export const DEFAULT_DIAL_CODE = "968";
export const DEFAULT_DIAL_ISO2 = "OM";

export const COUNTRY_DIAL_CODES: CountryDial[] = [
  { iso2: "OM", dial: "968", nameAr: "سلطنة عمان", nameEn: "Oman" },
  { iso2: "AF", dial: "93", nameAr: "أفغانستان", nameEn: "Afghanistan" },
  { iso2: "AL", dial: "355", nameAr: "ألبانيا", nameEn: "Albania" },
  { iso2: "DZ", dial: "213", nameAr: "الجزائر", nameEn: "Algeria" },
  { iso2: "AS", dial: "1684", nameAr: "ساموا الأمريكية", nameEn: "American Samoa" },
  { iso2: "AD", dial: "376", nameAr: "أندورا", nameEn: "Andorra" },
  { iso2: "AO", dial: "244", nameAr: "أنغولا", nameEn: "Angola" },
  { iso2: "AI", dial: "1264", nameAr: "أنغويلا", nameEn: "Anguilla" },
  { iso2: "AG", dial: "1268", nameAr: "أنتيغوا وبربودا", nameEn: "Antigua and Barbuda" },
  { iso2: "AR", dial: "54", nameAr: "الأرجنتين", nameEn: "Argentina" },
  { iso2: "AM", dial: "374", nameAr: "أرمينيا", nameEn: "Armenia" },
  { iso2: "AW", dial: "297", nameAr: "أروبا", nameEn: "Aruba" },
  { iso2: "AU", dial: "61", nameAr: "أستراليا", nameEn: "Australia" },
  { iso2: "AT", dial: "43", nameAr: "النمسا", nameEn: "Austria" },
  { iso2: "AZ", dial: "994", nameAr: "أذربيجان", nameEn: "Azerbaijan" },
  { iso2: "BS", dial: "1242", nameAr: "الباهاما", nameEn: "Bahamas" },
  { iso2: "BH", dial: "973", nameAr: "البحرين", nameEn: "Bahrain" },
  { iso2: "BD", dial: "880", nameAr: "بنغلاديش", nameEn: "Bangladesh" },
  { iso2: "BB", dial: "1246", nameAr: "بربادوس", nameEn: "Barbados" },
  { iso2: "BY", dial: "375", nameAr: "بيلاروس", nameEn: "Belarus" },
  { iso2: "BE", dial: "32", nameAr: "بلجيكا", nameEn: "Belgium" },
  { iso2: "BZ", dial: "501", nameAr: "بليز", nameEn: "Belize" },
  { iso2: "BJ", dial: "229", nameAr: "بنين", nameEn: "Benin" },
  { iso2: "BM", dial: "1441", nameAr: "برمودا", nameEn: "Bermuda" },
  { iso2: "BT", dial: "975", nameAr: "بوتان", nameEn: "Bhutan" },
  { iso2: "BO", dial: "591", nameAr: "بوليفيا", nameEn: "Bolivia" },
  { iso2: "BA", dial: "387", nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina" },
  { iso2: "BW", dial: "267", nameAr: "بوتسوانا", nameEn: "Botswana" },
  { iso2: "BR", dial: "55", nameAr: "البرازيل", nameEn: "Brazil" },
  { iso2: "IO", dial: "246", nameAr: "إقليم المحيط الهندي البريطاني", nameEn: "British Indian Ocean Territory" },
  { iso2: "VG", dial: "1284", nameAr: "جزر العذراء البريطانية", nameEn: "British Virgin Islands" },
  { iso2: "BN", dial: "673", nameAr: "بروناي", nameEn: "Brunei" },
  { iso2: "BG", dial: "359", nameAr: "بلغاريا", nameEn: "Bulgaria" },
  { iso2: "BF", dial: "226", nameAr: "بوركينا فاسو", nameEn: "Burkina Faso" },
  { iso2: "BI", dial: "257", nameAr: "بوروندي", nameEn: "Burundi" },
  { iso2: "KH", dial: "855", nameAr: "كمبوديا", nameEn: "Cambodia" },
  { iso2: "CM", dial: "237", nameAr: "الكاميرون", nameEn: "Cameroon" },
  { iso2: "CA", dial: "1", nameAr: "كندا", nameEn: "Canada" },
  { iso2: "CV", dial: "238", nameAr: "الرأس الأخضر", nameEn: "Cape Verde" },
  { iso2: "KY", dial: "1345", nameAr: "جزر كايمان", nameEn: "Cayman Islands" },
  { iso2: "CF", dial: "236", nameAr: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic" },
  { iso2: "TD", dial: "235", nameAr: "تشاد", nameEn: "Chad" },
  { iso2: "CL", dial: "56", nameAr: "تشيلي", nameEn: "Chile" },
  { iso2: "CN", dial: "86", nameAr: "الصين", nameEn: "China" },
  { iso2: "CX", dial: "61", nameAr: "جزيرة الكريسماس", nameEn: "Christmas Island" },
  { iso2: "CC", dial: "61", nameAr: "جزر كوكوس", nameEn: "Cocos Islands" },
  { iso2: "CO", dial: "57", nameAr: "كولومبيا", nameEn: "Colombia" },
  { iso2: "KM", dial: "269", nameAr: "جزر القمر", nameEn: "Comoros" },
  { iso2: "CG", dial: "242", nameAr: "الكونغو", nameEn: "Congo" },
  { iso2: "CD", dial: "243", nameAr: "الكونغو الديمقراطية", nameEn: "Congo (DRC)" },
  { iso2: "CK", dial: "682", nameAr: "جزر كوك", nameEn: "Cook Islands" },
  { iso2: "CR", dial: "506", nameAr: "كوستاريكا", nameEn: "Costa Rica" },
  { iso2: "CI", dial: "225", nameAr: "ساحل العاج", nameEn: "Côte d'Ivoire" },
  { iso2: "HR", dial: "385", nameAr: "كرواتيا", nameEn: "Croatia" },
  { iso2: "CU", dial: "53", nameAr: "كوبا", nameEn: "Cuba" },
  { iso2: "CW", dial: "599", nameAr: "كوراساو", nameEn: "Curaçao" },
  { iso2: "CY", dial: "357", nameAr: "قبرص", nameEn: "Cyprus" },
  { iso2: "CZ", dial: "420", nameAr: "التشيك", nameEn: "Czechia" },
  { iso2: "DK", dial: "45", nameAr: "الدنمارك", nameEn: "Denmark" },
  { iso2: "DJ", dial: "253", nameAr: "جيبوتي", nameEn: "Djibouti" },
  { iso2: "DM", dial: "1767", nameAr: "دومينيكا", nameEn: "Dominica" },
  { iso2: "DO", dial: "1809", nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic" },
  { iso2: "EC", dial: "593", nameAr: "الإكوادور", nameEn: "Ecuador" },
  { iso2: "EG", dial: "20", nameAr: "مصر", nameEn: "Egypt" },
  { iso2: "SV", dial: "503", nameAr: "السلفادور", nameEn: "El Salvador" },
  { iso2: "GQ", dial: "240", nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea" },
  { iso2: "ER", dial: "291", nameAr: "إريتريا", nameEn: "Eritrea" },
  { iso2: "EE", dial: "372", nameAr: "إستونيا", nameEn: "Estonia" },
  { iso2: "SZ", dial: "268", nameAr: "إسواتيني", nameEn: "Eswatini" },
  { iso2: "ET", dial: "251", nameAr: "إثيوبيا", nameEn: "Ethiopia" },
  { iso2: "FK", dial: "500", nameAr: "جزر فوكلاند", nameEn: "Falkland Islands" },
  { iso2: "FO", dial: "298", nameAr: "جزر فارو", nameEn: "Faroe Islands" },
  { iso2: "FJ", dial: "679", nameAr: "فيجي", nameEn: "Fiji" },
  { iso2: "FI", dial: "358", nameAr: "فنلندا", nameEn: "Finland" },
  { iso2: "FR", dial: "33", nameAr: "فرنسا", nameEn: "France" },
  { iso2: "GF", dial: "594", nameAr: "غويانا الفرنسية", nameEn: "French Guiana" },
  { iso2: "PF", dial: "689", nameAr: "بولينيزيا الفرنسية", nameEn: "French Polynesia" },
  { iso2: "GA", dial: "241", nameAr: "الغابون", nameEn: "Gabon" },
  { iso2: "GM", dial: "220", nameAr: "غامبيا", nameEn: "Gambia" },
  { iso2: "GE", dial: "995", nameAr: "جورجيا", nameEn: "Georgia" },
  { iso2: "DE", dial: "49", nameAr: "ألمانيا", nameEn: "Germany" },
  { iso2: "GH", dial: "233", nameAr: "غانا", nameEn: "Ghana" },
  { iso2: "GI", dial: "350", nameAr: "جبل طارق", nameEn: "Gibraltar" },
  { iso2: "GR", dial: "30", nameAr: "اليونان", nameEn: "Greece" },
  { iso2: "GL", dial: "299", nameAr: "غرينلاند", nameEn: "Greenland" },
  { iso2: "GD", dial: "1473", nameAr: "غرينادا", nameEn: "Grenada" },
  { iso2: "GP", dial: "590", nameAr: "غوادلوب", nameEn: "Guadeloupe" },
  { iso2: "GU", dial: "1671", nameAr: "غوام", nameEn: "Guam" },
  { iso2: "GT", dial: "502", nameAr: "غواتيمالا", nameEn: "Guatemala" },
  { iso2: "GG", dial: "44", nameAr: "غيرنزي", nameEn: "Guernsey" },
  { iso2: "GN", dial: "224", nameAr: "غينيا", nameEn: "Guinea" },
  { iso2: "GW", dial: "245", nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau" },
  { iso2: "GY", dial: "592", nameAr: "غيانا", nameEn: "Guyana" },
  { iso2: "HT", dial: "509", nameAr: "هايتي", nameEn: "Haiti" },
  { iso2: "HN", dial: "504", nameAr: "هندوراس", nameEn: "Honduras" },
  { iso2: "HK", dial: "852", nameAr: "هونغ كونغ", nameEn: "Hong Kong" },
  { iso2: "HU", dial: "36", nameAr: "المجر", nameEn: "Hungary" },
  { iso2: "IS", dial: "354", nameAr: "آيسلندا", nameEn: "Iceland" },
  { iso2: "IN", dial: "91", nameAr: "الهند", nameEn: "India" },
  { iso2: "ID", dial: "62", nameAr: "إندونيسيا", nameEn: "Indonesia" },
  { iso2: "IR", dial: "98", nameAr: "إيران", nameEn: "Iran" },
  { iso2: "IQ", dial: "964", nameAr: "العراق", nameEn: "Iraq" },
  { iso2: "IE", dial: "353", nameAr: "أيرلندا", nameEn: "Ireland" },
  { iso2: "IM", dial: "44", nameAr: "جزيرة مان", nameEn: "Isle of Man" },
  { iso2: "IL", dial: "972", nameAr: "إسرائيل", nameEn: "Israel" },
  { iso2: "IT", dial: "39", nameAr: "إيطاليا", nameEn: "Italy" },
  { iso2: "JM", dial: "1876", nameAr: "جامايكا", nameEn: "Jamaica" },
  { iso2: "JP", dial: "81", nameAr: "اليابان", nameEn: "Japan" },
  { iso2: "JE", dial: "44", nameAr: "جيرزي", nameEn: "Jersey" },
  { iso2: "JO", dial: "962", nameAr: "الأردن", nameEn: "Jordan" },
  { iso2: "KZ", dial: "7", nameAr: "كازاخستان", nameEn: "Kazakhstan" },
  { iso2: "KE", dial: "254", nameAr: "كينيا", nameEn: "Kenya" },
  { iso2: "KI", dial: "686", nameAr: "كيريباس", nameEn: "Kiribati" },
  { iso2: "XK", dial: "383", nameAr: "كوسوفو", nameEn: "Kosovo" },
  { iso2: "KW", dial: "965", nameAr: "الكويت", nameEn: "Kuwait" },
  { iso2: "KG", dial: "996", nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan" },
  { iso2: "LA", dial: "856", nameAr: "لاوس", nameEn: "Laos" },
  { iso2: "LV", dial: "371", nameAr: "لاتفيا", nameEn: "Latvia" },
  { iso2: "LB", dial: "961", nameAr: "لبنان", nameEn: "Lebanon" },
  { iso2: "LS", dial: "266", nameAr: "ليسوتو", nameEn: "Lesotho" },
  { iso2: "LR", dial: "231", nameAr: "ليبيريا", nameEn: "Liberia" },
  { iso2: "LY", dial: "218", nameAr: "ليبيا", nameEn: "Libya" },
  { iso2: "LI", dial: "423", nameAr: "ليختنشتاين", nameEn: "Liechtenstein" },
  { iso2: "LT", dial: "370", nameAr: "ليتوانيا", nameEn: "Lithuania" },
  { iso2: "LU", dial: "352", nameAr: "لوكسمبورغ", nameEn: "Luxembourg" },
  { iso2: "MO", dial: "853", nameAr: "ماكاو", nameEn: "Macao" },
  { iso2: "MG", dial: "261", nameAr: "مدغشقر", nameEn: "Madagascar" },
  { iso2: "MW", dial: "265", nameAr: "ملاوي", nameEn: "Malawi" },
  { iso2: "MY", dial: "60", nameAr: "ماليزيا", nameEn: "Malaysia" },
  { iso2: "MV", dial: "960", nameAr: "المالديف", nameEn: "Maldives" },
  { iso2: "ML", dial: "223", nameAr: "مالي", nameEn: "Mali" },
  { iso2: "MT", dial: "356", nameAr: "مالطا", nameEn: "Malta" },
  { iso2: "MH", dial: "692", nameAr: "جزر مارشال", nameEn: "Marshall Islands" },
  { iso2: "MQ", dial: "596", nameAr: "مارتينيك", nameEn: "Martinique" },
  { iso2: "MR", dial: "222", nameAr: "موريتانيا", nameEn: "Mauritania" },
  { iso2: "MU", dial: "230", nameAr: "موريشيوس", nameEn: "Mauritius" },
  { iso2: "YT", dial: "262", nameAr: "مايوت", nameEn: "Mayotte" },
  { iso2: "MX", dial: "52", nameAr: "المكسيك", nameEn: "Mexico" },
  { iso2: "FM", dial: "691", nameAr: "ميكرونيزيا", nameEn: "Micronesia" },
  { iso2: "MD", dial: "373", nameAr: "مولدوفا", nameEn: "Moldova" },
  { iso2: "MC", dial: "377", nameAr: "موناكو", nameEn: "Monaco" },
  { iso2: "MN", dial: "976", nameAr: "منغوليا", nameEn: "Mongolia" },
  { iso2: "ME", dial: "382", nameAr: "الجبل الأسود", nameEn: "Montenegro" },
  { iso2: "MS", dial: "1664", nameAr: "مونتسرات", nameEn: "Montserrat" },
  { iso2: "MA", dial: "212", nameAr: "المغرب", nameEn: "Morocco" },
  { iso2: "MZ", dial: "258", nameAr: "موزمبيق", nameEn: "Mozambique" },
  { iso2: "MM", dial: "95", nameAr: "ميانمار", nameEn: "Myanmar" },
  { iso2: "NA", dial: "264", nameAr: "ناميبيا", nameEn: "Namibia" },
  { iso2: "NR", dial: "674", nameAr: "ناورو", nameEn: "Nauru" },
  { iso2: "NP", dial: "977", nameAr: "نيبال", nameEn: "Nepal" },
  { iso2: "NL", dial: "31", nameAr: "هولندا", nameEn: "Netherlands" },
  { iso2: "NC", dial: "687", nameAr: "كاليدونيا الجديدة", nameEn: "New Caledonia" },
  { iso2: "NZ", dial: "64", nameAr: "نيوزيلندا", nameEn: "New Zealand" },
  { iso2: "NI", dial: "505", nameAr: "نيكاراغوا", nameEn: "Nicaragua" },
  { iso2: "NE", dial: "227", nameAr: "النيجر", nameEn: "Niger" },
  { iso2: "NG", dial: "234", nameAr: "نيجيريا", nameEn: "Nigeria" },
  { iso2: "NU", dial: "683", nameAr: "نيوي", nameEn: "Niue" },
  { iso2: "NF", dial: "672", nameAr: "جزيرة نورفولك", nameEn: "Norfolk Island" },
  { iso2: "KP", dial: "850", nameAr: "كوريا الشمالية", nameEn: "North Korea" },
  { iso2: "MK", dial: "389", nameAr: "مقدونيا الشمالية", nameEn: "North Macedonia" },
  { iso2: "MP", dial: "1670", nameAr: "جزر ماريانا الشمالية", nameEn: "Northern Mariana Islands" },
  { iso2: "NO", dial: "47", nameAr: "النرويج", nameEn: "Norway" },
  { iso2: "PK", dial: "92", nameAr: "باكستان", nameEn: "Pakistan" },
  { iso2: "PW", dial: "680", nameAr: "بالاو", nameEn: "Palau" },
  { iso2: "PS", dial: "970", nameAr: "فلسطين", nameEn: "Palestine" },
  { iso2: "PA", dial: "507", nameAr: "بنما", nameEn: "Panama" },
  { iso2: "PG", dial: "675", nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea" },
  { iso2: "PY", dial: "595", nameAr: "باراغواي", nameEn: "Paraguay" },
  { iso2: "PE", dial: "51", nameAr: "بيرو", nameEn: "Peru" },
  { iso2: "PH", dial: "63", nameAr: "الفلبين", nameEn: "Philippines" },
  { iso2: "PL", dial: "48", nameAr: "بولندا", nameEn: "Poland" },
  { iso2: "PT", dial: "351", nameAr: "البرتغال", nameEn: "Portugal" },
  { iso2: "PR", dial: "1787", nameAr: "بورتوريكو", nameEn: "Puerto Rico" },
  { iso2: "QA", dial: "974", nameAr: "قطر", nameEn: "Qatar" },
  { iso2: "RE", dial: "262", nameAr: "ريونيون", nameEn: "Réunion" },
  { iso2: "RO", dial: "40", nameAr: "رومانيا", nameEn: "Romania" },
  { iso2: "RU", dial: "7", nameAr: "روسيا", nameEn: "Russia" },
  { iso2: "RW", dial: "250", nameAr: "رواندا", nameEn: "Rwanda" },
  { iso2: "BL", dial: "590", nameAr: "سان بارتليمي", nameEn: "Saint Barthélemy" },
  { iso2: "SH", dial: "290", nameAr: "سانت هيلينا", nameEn: "Saint Helena" },
  { iso2: "KN", dial: "1869", nameAr: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis" },
  { iso2: "LC", dial: "1758", nameAr: "سانت لوسيا", nameEn: "Saint Lucia" },
  { iso2: "MF", dial: "590", nameAr: "سانت مارتن", nameEn: "Saint Martin" },
  { iso2: "PM", dial: "508", nameAr: "سان بيير وميكلون", nameEn: "Saint Pierre and Miquelon" },
  { iso2: "VC", dial: "1784", nameAr: "سانت فنسنت", nameEn: "Saint Vincent and the Grenadines" },
  { iso2: "WS", dial: "685", nameAr: "ساموا", nameEn: "Samoa" },
  { iso2: "SM", dial: "378", nameAr: "سان مارينو", nameEn: "San Marino" },
  { iso2: "ST", dial: "239", nameAr: "ساو تومي وبرينسيبي", nameEn: "São Tomé and Príncipe" },
  { iso2: "SA", dial: "966", nameAr: "السعودية", nameEn: "Saudi Arabia" },
  { iso2: "SN", dial: "221", nameAr: "السنغال", nameEn: "Senegal" },
  { iso2: "RS", dial: "381", nameAr: "صربيا", nameEn: "Serbia" },
  { iso2: "SC", dial: "248", nameAr: "سيشل", nameEn: "Seychelles" },
  { iso2: "SL", dial: "232", nameAr: "سيراليون", nameEn: "Sierra Leone" },
  { iso2: "SG", dial: "65", nameAr: "سنغافورة", nameEn: "Singapore" },
  { iso2: "SX", dial: "1721", nameAr: "سينت مارتن", nameEn: "Sint Maarten" },
  { iso2: "SK", dial: "421", nameAr: "سلوفاكيا", nameEn: "Slovakia" },
  { iso2: "SI", dial: "386", nameAr: "سلوفينيا", nameEn: "Slovenia" },
  { iso2: "SB", dial: "677", nameAr: "جزر سليمان", nameEn: "Solomon Islands" },
  { iso2: "SO", dial: "252", nameAr: "الصومال", nameEn: "Somalia" },
  { iso2: "ZA", dial: "27", nameAr: "جنوب أفريقيا", nameEn: "South Africa" },
  { iso2: "KR", dial: "82", nameAr: "كوريا الجنوبية", nameEn: "South Korea" },
  { iso2: "SS", dial: "211", nameAr: "جنوب السودان", nameEn: "South Sudan" },
  { iso2: "ES", dial: "34", nameAr: "إسبانيا", nameEn: "Spain" },
  { iso2: "LK", dial: "94", nameAr: "سريلانكا", nameEn: "Sri Lanka" },
  { iso2: "SD", dial: "249", nameAr: "السودان", nameEn: "Sudan" },
  { iso2: "SR", dial: "597", nameAr: "سورينام", nameEn: "Suriname" },
  { iso2: "SE", dial: "46", nameAr: "السويد", nameEn: "Sweden" },
  { iso2: "CH", dial: "41", nameAr: "سويسرا", nameEn: "Switzerland" },
  { iso2: "SY", dial: "963", nameAr: "سوريا", nameEn: "Syria" },
  { iso2: "TW", dial: "886", nameAr: "تايوان", nameEn: "Taiwan" },
  { iso2: "TJ", dial: "992", nameAr: "طاجيكستان", nameEn: "Tajikistan" },
  { iso2: "TZ", dial: "255", nameAr: "تنزانيا", nameEn: "Tanzania" },
  { iso2: "TH", dial: "66", nameAr: "تايلاند", nameEn: "Thailand" },
  { iso2: "TL", dial: "670", nameAr: "تيمور الشرقية", nameEn: "Timor-Leste" },
  { iso2: "TG", dial: "228", nameAr: "توغو", nameEn: "Togo" },
  { iso2: "TK", dial: "690", nameAr: "توكيلاو", nameEn: "Tokelau" },
  { iso2: "TO", dial: "676", nameAr: "تونغا", nameEn: "Tonga" },
  { iso2: "TT", dial: "1868", nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago" },
  { iso2: "TN", dial: "216", nameAr: "تونس", nameEn: "Tunisia" },
  { iso2: "TR", dial: "90", nameAr: "تركيا", nameEn: "Turkey" },
  { iso2: "TM", dial: "993", nameAr: "تركمانستان", nameEn: "Turkmenistan" },
  { iso2: "TC", dial: "1649", nameAr: "جزر توركس وكايكوس", nameEn: "Turks and Caicos Islands" },
  { iso2: "TV", dial: "688", nameAr: "توفالو", nameEn: "Tuvalu" },
  { iso2: "VI", dial: "1340", nameAr: "جزر العذراء الأمريكية", nameEn: "U.S. Virgin Islands" },
  { iso2: "UG", dial: "256", nameAr: "أوغندا", nameEn: "Uganda" },
  { iso2: "UA", dial: "380", nameAr: "أوكرانيا", nameEn: "Ukraine" },
  { iso2: "AE", dial: "971", nameAr: "الإمارات", nameEn: "United Arab Emirates" },
  { iso2: "GB", dial: "44", nameAr: "المملكة المتحدة", nameEn: "United Kingdom" },
  { iso2: "US", dial: "1", nameAr: "الولايات المتحدة", nameEn: "United States" },
  { iso2: "UY", dial: "598", nameAr: "أوروغواي", nameEn: "Uruguay" },
  { iso2: "UZ", dial: "998", nameAr: "أوزبكستان", nameEn: "Uzbekistan" },
  { iso2: "VU", dial: "678", nameAr: "فانواتو", nameEn: "Vanuatu" },
  { iso2: "VA", dial: "379", nameAr: "الفاتيكان", nameEn: "Vatican City" },
  { iso2: "VE", dial: "58", nameAr: "فنزويلا", nameEn: "Venezuela" },
  { iso2: "VN", dial: "84", nameAr: "فيتنام", nameEn: "Vietnam" },
  { iso2: "WF", dial: "681", nameAr: "واليس وفوتونا", nameEn: "Wallis and Futuna" },
  { iso2: "EH", dial: "212", nameAr: "الصحراء الغربية", nameEn: "Western Sahara" },
  { iso2: "YE", dial: "967", nameAr: "اليمن", nameEn: "Yemen" },
  { iso2: "ZM", dial: "260", nameAr: "زامبيا", nameEn: "Zambia" },
  { iso2: "ZW", dial: "263", nameAr: "زيمبابوي", nameEn: "Zimbabwe" },
];

const dialsByLengthDesc = [...new Set(COUNTRY_DIAL_CODES.map((item) => item.dial))].sort((a, b) => b.length - a.length);

/** Oman pinned first, then alphabetical by locale name. */
export function dialCodesForSelect(locale: "ar" | "en") {
  const oman = COUNTRY_DIAL_CODES.find((item) => item.iso2 === DEFAULT_DIAL_ISO2)!;
  const rest = COUNTRY_DIAL_CODES
    .filter((item) => item.iso2 !== DEFAULT_DIAL_ISO2)
    .slice()
    .sort((a, b) => (locale === "ar" ? a.nameAr.localeCompare(b.nameAr, "ar") : a.nameEn.localeCompare(b.nameEn, "en")));
  return [oman, ...rest];
}

export function findCountryByIso2(iso2: string) {
  return COUNTRY_DIAL_CODES.find((item) => item.iso2 === iso2) ?? COUNTRY_DIAL_CODES[0];
}

export function findCountryByDial(dial: string) {
  const digits = String(dial ?? "").replace(/\D/g, "");
  return COUNTRY_DIAL_CODES.find((item) => item.dial === digits)
    ?? COUNTRY_DIAL_CODES.find((item) => item.iso2 === DEFAULT_DIAL_ISO2)!;
}

/** Prefer longest dial match so +1684 beats +1. */
export function matchDialPrefix(digits: string) {
  const value = String(digits ?? "").replace(/\D/g, "");
  for (const dial of dialsByLengthDesc) {
    if (value.startsWith(dial) && value.length > dial.length) return dial;
  }
  return DEFAULT_DIAL_CODE;
}
